/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAuthenticatedRouteRouteImport } from './routes/$lang/_authenticated/route'
import { Route as LangCrearVideoRouteImport } from './routes/$lang/crear-video'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangSubirRouteImport } from './routes/$lang/subir'
import { Route as LangAuthenticatedPanelRouteImport } from './routes/$lang/_authenticated/panel'
import { Route as LangEstadosSlugRouteImport } from './routes/$lang/estados.$slug'
import { Route as ApiPublicVideoJobsRouteImport } from './routes/api/public/video-jobs'
import { Route as ApiPublicVideoUploadRouteImport } from './routes/api/public/video-upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthenticatedRouteRoute = LangAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCrearVideoRoute = LangCrearVideoRouteImport.update({
  id: '/crear-video',
  path: '/crear-video',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubirRoute = LangSubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthenticatedPanelRoute = LangAuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => LangAuthenticatedRouteRoute,
} as any)
const LangEstadosSlugRoute = LangEstadosSlugRouteImport.update({
  id: '/estados/$slug',
  path: '/estados/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiPublicVideoJobsRoute = ApiPublicVideoJobsRouteImport.update({
  id: '/api/public/video-jobs',
  path: '/api/public/video-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoUploadRoute = ApiPublicVideoUploadRouteImport.update({
  id: '/api/public/video-upload',
  path: '/api/public/video-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/crear-video': typeof LangCrearVideoRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
  '/api/public/video-jobs': typeof ApiPublicVideoJobsRoute
  '/api/public/video-upload': typeof ApiPublicVideoUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/crear-video': typeof LangCrearVideoRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/$lang/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
  '/api/public/video-jobs': typeof ApiPublicVideoJobsRoute
  '/api/public/video-upload': typeof ApiPublicVideoUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_authenticated': typeof LangAuthenticatedRouteRouteWithChildren
  '/$lang/crear-video': typeof LangCrearVideoRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_authenticated/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
  '/api/public/video-jobs': typeof ApiPublicVideoJobsRoute
  '/api/public/video-upload': typeof ApiPublicVideoUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/crear-video'
    | '/$lang/login'
    | '/$lang/subir'
    | '/$lang/'
    | '/$lang/panel'
    | '/$lang/estados/$slug'
    | '/api/public/video-jobs'
    | '/api/public/video-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/crear-video'
    | '/$lang/login'
    | '/$lang/subir'
    | '/$lang/panel'
    | '/$lang/estados/$slug'
    | '/api/public/video-jobs'
    | '/api/public/video-upload'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_authenticated'
    | '/$lang/crear-video'
    | '/$lang/login'
    | '/$lang/subir'
    | '/$lang/'
    | '/$lang/_authenticated/panel'
    | '/$lang/estados/$slug'
    | '/api/public/video-jobs'
    | '/api/public/video-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  ApiPublicVideoJobsRoute: typeof ApiPublicVideoJobsRoute
  ApiPublicVideoUploadRoute: typeof ApiPublicVideoUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_authenticated': {
      id: '/$lang/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/crear-video': {
      id: '/$lang/crear-video'
      path: '/crear-video'
      fullPath: '/$lang/crear-video'
      preLoaderRoute: typeof LangCrearVideoRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subir': {
      id: '/$lang/subir'
      path: '/subir'
      fullPath: '/$lang/subir'
      preLoaderRoute: typeof LangSubirRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_authenticated/panel': {
      id: '/$lang/_authenticated/panel'
      path: '/panel'
      fullPath: '/$lang/panel'
      preLoaderRoute: typeof LangAuthenticatedPanelRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/estados/$slug': {
      id: '/$lang/estados/$slug'
      path: '/estados/$slug'
      fullPath: '/$lang/estados/$slug'
      preLoaderRoute: typeof LangEstadosSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/public/video-jobs': {
      id: '/api/public/video-jobs'
      path: '/api/public/video-jobs'
      fullPath: '/api/public/video-jobs'
      preLoaderRoute: typeof ApiPublicVideoJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-upload': {
      id: '/api/public/video-upload'
      path: '/api/public/video-upload'
      fullPath: '/api/public/video-upload'
      preLoaderRoute: typeof ApiPublicVideoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangAuthenticatedRouteRouteChildren {
  LangAuthenticatedPanelRoute: typeof LangAuthenticatedPanelRoute
}

const LangAuthenticatedRouteRouteChildren: LangAuthenticatedRouteRouteChildren =
  {
    LangAuthenticatedPanelRoute: LangAuthenticatedPanelRoute,
  }

const LangAuthenticatedRouteRouteWithChildren =
  LangAuthenticatedRouteRoute._addFileChildren(
    LangAuthenticatedRouteRouteChildren,
  )

interface LangRouteRouteChildren {
  LangAuthenticatedRouteRoute: typeof LangAuthenticatedRouteRouteWithChildren
  LangCrearVideoRoute: typeof LangCrearVideoRoute
  LangLoginRoute: typeof LangLoginRoute
  LangSubirRoute: typeof LangSubirRoute
  LangIndexRoute: typeof LangIndexRoute
  LangEstadosSlugRoute: typeof LangEstadosSlugRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAuthenticatedRouteRoute: LangAuthenticatedRouteRouteWithChildren,
  LangCrearVideoRoute: LangCrearVideoRoute,
  LangLoginRoute: LangLoginRoute,
  LangSubirRoute: LangSubirRoute,
  LangIndexRoute: LangIndexRoute,
  LangEstadosSlugRoute: LangEstadosSlugRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  ApiPublicVideoJobsRoute: ApiPublicVideoJobsRoute,
  ApiPublicVideoUploadRoute: ApiPublicVideoUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
