/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SubirRouteImport } from './routes/subir'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAuthenticatedRouteRouteImport } from './routes/$lang/_authenticated/route'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangSubirRouteImport } from './routes/$lang/subir'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as EstadosSlugRouteImport } from './routes/estados.$slug'
import { Route as LangAuthenticatedPanelRouteImport } from './routes/$lang/_authenticated/panel'
import { Route as LangEstadosSlugRouteImport } from './routes/$lang/estados.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubirRoute = SubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthenticatedRouteRoute = LangAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSubirRoute = LangSubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => LangRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EstadosSlugRoute = EstadosSlugRouteImport.update({
  id: '/estados/$slug',
  path: '/estados/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthenticatedPanelRoute = LangAuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => LangAuthenticatedRouteRoute,
} as any)
const LangEstadosSlugRoute = LangEstadosSlugRouteImport.update({
  id: '/estados/$slug',
  path: '/estados/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/subir': typeof SubirRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/estados/$slug': typeof EstadosSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subir': typeof SubirRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/estados/$slug': typeof EstadosSlugRoute
  '/$lang/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/subir': typeof SubirRoute
  '/$lang/_authenticated': typeof LangAuthenticatedRouteRouteWithChildren
  '/$lang/login': typeof LangLoginRoute
  '/$lang/subir': typeof LangSubirRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/estados/$slug': typeof EstadosSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_authenticated/panel': typeof LangAuthenticatedPanelRoute
  '/$lang/estados/$slug': typeof LangEstadosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/login'
    | '/subir'
    | '/$lang/login'
    | '/$lang/subir'
    | '/panel'
    | '/estados/$slug'
    | '/$lang/'
    | '/$lang/panel'
    | '/$lang/estados/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/subir'
    | '/$lang'
    | '/$lang/login'
    | '/$lang/subir'
    | '/panel'
    | '/estados/$slug'
    | '/$lang/panel'
    | '/$lang/estados/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/_authenticated'
    | '/login'
    | '/subir'
    | '/$lang/_authenticated'
    | '/$lang/login'
    | '/$lang/subir'
    | '/_authenticated/panel'
    | '/estados/$slug'
    | '/$lang/'
    | '/$lang/_authenticated/panel'
    | '/$lang/estados/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubirRoute: typeof SubirRoute
  EstadosSlugRoute: typeof EstadosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subir': {
      id: '/subir'
      path: '/subir'
      fullPath: '/subir'
      preLoaderRoute: typeof SubirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_authenticated': {
      id: '/$lang/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/subir': {
      id: '/$lang/subir'
      path: '/subir'
      fullPath: '/$lang/subir'
      preLoaderRoute: typeof LangSubirRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/estados/$slug': {
      id: '/estados/$slug'
      path: '/estados/$slug'
      fullPath: '/estados/$slug'
      preLoaderRoute: typeof EstadosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_authenticated/panel': {
      id: '/$lang/_authenticated/panel'
      path: '/panel'
      fullPath: '/$lang/panel'
      preLoaderRoute: typeof LangAuthenticatedPanelRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/estados/$slug': {
      id: '/$lang/estados/$slug'
      path: '/estados/$slug'
      fullPath: '/$lang/estados/$slug'
      preLoaderRoute: typeof LangEstadosSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangAuthenticatedRouteRouteChildren {
  LangAuthenticatedPanelRoute: typeof LangAuthenticatedPanelRoute
}

const LangAuthenticatedRouteRouteChildren: LangAuthenticatedRouteRouteChildren =
  {
    LangAuthenticatedPanelRoute: LangAuthenticatedPanelRoute,
  }

const LangAuthenticatedRouteRouteWithChildren =
  LangAuthenticatedRouteRoute._addFileChildren(
    LangAuthenticatedRouteRouteChildren,
  )

interface LangRouteRouteChildren {
  LangAuthenticatedRouteRoute: typeof LangAuthenticatedRouteRouteWithChildren
  LangLoginRoute: typeof LangLoginRoute
  LangSubirRoute: typeof LangSubirRoute
  LangIndexRoute: typeof LangIndexRoute
  LangEstadosSlugRoute: typeof LangEstadosSlugRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAuthenticatedRouteRoute: LangAuthenticatedRouteRouteWithChildren,
  LangLoginRoute: LangLoginRoute,
  LangSubirRoute: LangSubirRoute,
  LangIndexRoute: LangIndexRoute,
  LangEstadosSlugRoute: LangEstadosSlugRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SubirRoute: SubirRoute,
  EstadosSlugRoute: EstadosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
